Workaround for missing PBR requirement
PBR misses a requirement to testrepository.
This workaround installs it in front and can be removed after
PBR is fixed.

This fix also contains tox fix due to the fact that kilo gate is broken two
times which can't be fixed in two dependent commits:

  Do not fail with Tox 2.3.1

  Latest tox causes failures:
     File "/usr/local/lib/python2.7/dist-packages/tox/config.py", line 1140, in processcommand
      argv = list(shlexer)
     File "/usr/lib/python2.7/shlex.py", line 269, in next
       token = self.get_token()
     File "/usr/lib/python2.7/shlex.py", line 96, in get_token
       raw = self.read_token()
     File "/usr/lib/python2.7/shlex.py", line 172, in read_token
       raise ValueError, "No closing quotation"
   ValueError: No closing quotation

  This is caused by a backwards incompatible change in tox:
  https://bitbucket.org/hpk42/tox/issues/181
  (cherry picked from commit f59e6df23a430f0622215fec5bbbe18cfe7fee9c)

Change-Id: Iddce0260436042e37eebe2aecb810707e53a4473
Partial-Bug: #1530026